name: emoHep_yhl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2024.3.11=h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=23.3=py39h06a4308_0
  - python=3.9.0=hdb3f193_2
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - addict==2.4.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - axial-positional-embedding==0.2.1
      - blessed==1.20.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - colt5-attention==0.10.15
      - contourpy==1.2.0
      - cycler==0.12.1
      - decorator==5.1.1
      - dill==0.3.7
      - docopt==0.6.2
      - einops==0.6.1
      - fire==0.6.0
      - flash-attn==2.3.6
      - fonttools==4.44.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.1.3
      - future==1.0.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - gpustat==1.1.1
      - grpcio==1.59.2
      - h5py==3.8.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning-lite==1.8.0
      - lightning-utilities==0.11.0
      - linear-attention-transformer==0.19.1
      - linformer==0.2.1
      - local-attention==1.9.0
      - loguru==0.6.0
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.6.2
      - mne==1.3.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.24.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - packaging==23.2
      - pandarallel==1.6.5
      - pandas==1.5.3
      - parse==1.20.1
      - pillow==10.1.0
      - pipreqs==0.4.13
      - platformdirs==3.11.0
      - pooch==1.8.0
      - product-key-memory==0.2.10
      - protobuf==4.23.4
      - psutil==5.9.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pydeprecate==0.3.1
      - pyelftools==0.31
      - pyhealth==1.1.4
      - pykalman==0.10.1
      - pyparsing==3.1.1
      - pysmb==1.2.9.1
      - python-dateutil==2.8.2
      - pytorch-lightning==1.9.4
      - pytz==2023.3.post1
      - pyyaml==5.4.1
      - pyyaml-include==1.2
      - rdkit==2023.9.1
      - reformer-pytorch==1.4.4
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-base==0.12.0
      - scikit-learn==1.2.2
      - scipy==1.9.3
      - seaborn==0.12.2
      - sympy==1.14.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - timm==0.3.2
      - tinydb==4.8.2
      - torch==1.13.1
      - torch-geometric==2.6.1
      - torchmetrics==0.11.4
      - torchsummary==1.5.1
      - torchvision==0.14.1
      - tqdm==4.64.1
      - typing-extensions==4.15.0
      - unix-ar==0.2.1
      - urllib3==1.26.15
      - wcwidth==0.2.12
      - werkzeug==3.0.1
      - wget==3.2
      - yarg==0.1.9
      - yarl==1.9.4
      - zipp==3.17.0
      - zstandard==0.22.0
prefix: /home/jiangweibang/miniconda3/envs/emoHep_yhl
